[env:esp32s3]
framework = espidf
board = esp32-s3-devkitc-1
platform = espressif32@6.9.0 ; espressif framework version we are using

upload_protocol = esptool

build_flags =
  -std=gnu++20 ; c++ version set to c++20
    
extra_scripts = 
    pre:send_flash_command.py